version: "3"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    environment: &mate-environment
      CONTAINER_ROLE: web
      DB_HOST: ${DB_HOST:-database}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-languagemate}
      DB_USERNAME: ${DB_USERNAME:-languagemate}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-R0OTp@ssword}
      DB_PASSWORD: ${DB_PASSWORD:-Passw0rd}
      DB_DRIVER: ${DB_DRIVER:-mysql}
    ports:
      - "${API_EXPOSE_PORT}:8000"
      
  database:
    image: mariadb:10.3
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-R0OTp@ssword}
      MYSQL_DATABASE: ${DB_DATABASE:-languagemate}
      MYSQL_USER: ${DB_USERNAME:-languagemate}
      MYSQL_PASSWORD: ${DB_PASSWORD:-Passw0rd}
      TZ: ${DB_TIMEZONE:-Asia/Shanghai}
    healthcheck:
      test: ["CMD", "mysql", "-u", "${DB_USERNAME:-languagemate}", "-p${DB_PASSWORD:-languagemate}", "-e", "SELECT 1"]
      start_period: 3s
      timeout: 3s
      retries: 5
    volumes:
      - ./manifest/database/:/var/database
      - database:/var/lib/mysql
    command:
      mysqld --default-time-zone=${DB_TIMEZONE:-Asia/Shanghai} --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - "${DB_EXPOSE_PORT}:3306"

volumes:
  database:
  redis: