// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package word

import (
	"backend/api/word"
)

type ControllerV1 struct{}

func NewV1() word.IWordV1 {
	return &ControllerV1{}
}
