// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"backend/internal/dao/internal"
)

// internalUserWordDao is internal type for wrapping internal DAO implements.
type internalUserWordDao = *internal.UserWordDao

// userWordDao is the data access object for table user_word.
// You can define custom methods on it to extend its functionality as you wish.
type userWordDao struct {
	internalUserWordDao
}

var (
	// UserWord is globally public accessible object for table user_word operations.
	UserWord = userWordDao{
		internal.NewUserWordDao(),
	}
)

// Fill with you ideas below.
